# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
# env = GDK_SCALE,2
monitor=eDP-1, 1366x768@60, auto, 1
monitorv2 {
    output = DP-1
    mode = 1920x1200@59.95
    scale = 1.5
    # position 
}

# monitor=DP-1, 1920x1080@59.95, auto, 1, 
